function vc {
  vpn cisco "$1"
}

function vf {
  vpn forti "$1"
}

function vpn {
  local TYPE=$1
  local TOKEN=$2

  VPN_LOG_PATH=~/.vpnlog

  # kill existing VPN connection when ran without the token argument
  if [[ "${TOKEN}" == "" ]]
  then
    pgrep openconnect > /dev/null && echo "Stopping VPN connection" && sudo VPN_TYPE="${TYPE}" pkill openconnect
    return
  fi

  # report that a VPN connection is already open
  if pgrep openconnect > /dev/null
  then
    VPN_COMMAND=$(pgrep -lf openconnect)
    VPN_TYPE=${VPN_COMMAND##*-}
    echo "A ${VPN_TYPE} VPN instance is already running"
    return
  fi

  echo "Starting VPN connection"

  if [[ "${TYPE}" == "cisco" ]]
  then
    CREDS="${CISCO_RSA_PIN}${TOKEN}"
  else
    CREDS="${FORTI_PASSWORD}\n${TOKEN}\n"
  fi

  # the VPN_TYPE will be used in the connection hooks to determine actions based on which VPN type is used
  echo "${CREDS}" | sudo VPN_TYPE="${TYPE}" openconnect --background --config ~/".vpn-${TYPE}" > "${VPN_LOG_PATH}" 2>&1

  sleep 1

  if ! pgrep openconnect > /dev/null
  then
    echo "VPN connection failed"
    tail "${VPN_LOG_PATH}"
    return 1
  fi

  echo "Logs will be written to ${VPN_LOG_PATH}"
}
