function vc {
  vpn cisco "$1"
}

function vf {
  vpn forti "$1"
}

function delete_resolvers {
  if [ -d /etc/resolver ]
  then
    sudo rm -rf /etc/resolver/
  fi
}

function vpn {
  local TYPE=$1
  local TOKEN=$2

  VPN_LOG_PATH=~/.vpnlog

  delete_resolvers

  # kill existing VPN connection when ran without the token argument
  if [[ "${TOKEN}" == "" ]]
  then
    pgrep openconnect > /dev/null && echo "Stopping VPN connection" && sudo pkill openconnect
    return
  fi

  echo "Starting VPN connection"
  echo "Logs will be written to ${VPN_LOG_PATH}"

  if [[ "${TYPE}" == "cisco" ]]
  then
    CREDS="${CISCO_RSA_PIN}${TOKEN}"
  else
    CREDS="${FORTI_PASSWORD}\n${TOKEN}\n"
  fi

  echo "${CREDS}" | sudo openconnect --background --config ~/".vpn-${TYPE}" > "${VPN_LOG_PATH}" 2>&1

  if [[ "${TYPE}" == "forti" && -d ~/.vpn-forti-resolver ]]
  then
    sudo cp -r ~/.vpn-forti-resolver/ /etc/resolver/
  fi
}
